website/models.py
import math
from flask import Blueprint
import os
import glob

models = Blueprint('models', __name__)
# Square root curve

def square_curve(orig, new_grades):
        for grade in orig:
            new_grade = round(math.sqrt(grade) * 10, 2)
            new_grades.append(new_grade)
        return new_grades


# Determines the amount to add to all scores
def modifier(grade):
    if grade >= 90 and grade <= 100:
        curved_mod = (100 - grade)
    elif grade >= 80 and grade < 90:
        curved_mod = (90 - grade)
    elif grade >= 70 and grade < 80:
        curved_mod = (80 - grade)
    elif grade >= 60 and grade < 70:
        curved_mod = (70 - grade)
    else:
        curved_mod = (60 - grade)
    return curved_mod


# Adds the modifier to the original score
def max_curve(curved_mod, orig, new_grades):
    for grade in orig:
        curved_grade = round(grade + curved_mod, 2)
        new_grades.append(curved_grade)
    return new_grades


# 10 point curve function
def ten_point(orig, new_grades):
    for grade in orig:
        curved_grade = round(grade + 10, 2)
        new_grades.append(curved_grade)
    return new_grades

def delete_downloads(DOWN_PATH):
    try:
        cwd = os.getcwd()
        extension = "csv"
        os.chdir(DOWN_PATH)
        result = glob.glob('*.{}'.format(extension))
        for file in result:
            os.remove(file)
        os.chdir(cwd)
        return "success"
    except FileNotFoundError as error:
        return "error"

def delete_uploads(UP_PATH):
    try:
        cwd = os.getcwd()
        extension = "csv"
        os.chdir(UP_PATH)
        result = glob.glob('*.{}'.format(extension))
        for file in result:
            os.remove(file)
        os.chdir(cwd)
        return "success"
    except FileNotFoundError:
        return "error"

website/__init__.py
from flask import Flask
import os
PROJ_STATUS = "prod"
ALLOWED_EXTENSIONS = {'csv'}

def create_app():
    app = Flask(__name__)

    app.config['UPLOAD_FOLDER'] = "uploads"
    app.config['MAX_CONTENT_LENGTH'] = 5 * 1000 * 1000
    app.config['ALLOWED_EXTENSIONS'] = ALLOWED_EXTENSIONS
    app.config['SECRET_KEY'] = os.environ.get('APP_SECRET')
    if PROJ_STATUS == "dev":
        app.config['SECRET_KEY'] ="secret"
        app.debug = True
    else:
        app.debug = False

    from .views import views
    from .models import models

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(models, url_prefix='/')

    return app

website/views.py
from flask import Blueprint, render_template, request, flash, redirect
from werkzeug.utils import secure_filename
import pandas as pd
from .models import delete_uploads, square_curve, modifier, max_curve, ten_point, delete_downloads, delete_uploads

import os

UP_PATH = "website/static/uploads"
DOWN_PATH = "website/static/downloads"
ALLOWED_EXTENSIONS = {'csv'}

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
def home():
    cwd = os.getcwd()
    # should remove files that are in downloads and uploads folder
    delete_downloads(DOWN_PATH)  
    delete_uploads(UP_PATH)
    flash("Previous files deleted", category="success")
    # Gets info from form and saves file to upload folder

    if request.method == "POST":

        file = request.files['file']
        # print(file.filename)
        if file.filename == "":
            flash(message="No selected file", category="error")
            return redirect(request.url)
        if file.filename.rsplit('.', 1)[1].lower()=='csv':
            filename = secure_filename(file.filename)
            file.save(os.path.join(UP_PATH, filename))
        else:
            flash(message="Incorrect file type.", category="error")
            return redirect(request.url)
            

        column_name = request.form.get('curved-col')
        curve_option = request.form.get('curve-apply')
        curved_file = f"{request.form.get('curved-file')}.csv"
        if column_name == "" or curve_option == "Choose the curve you want to apply." or curved_file == ".csv":
            flash(message="Ensure all fields are filled out", category="error")

        # Get the Data Frame
        grades = pd.read_csv(os.path.join(UP_PATH, file.filename))
        # print(grades)
        new_grades = []
        if column_name in grades.columns:
            orig = grades[column_name]
            highest = max(orig)
        else:
            flash(message=f"There is no column named {column_name}", category="error")
            return redirect(request.url)
        # Curved Options
        try:
            if curve_option == "1":
                square_curve(orig=orig, new_grades=new_grades)
            elif curve_option == "2":
                curved_mod = modifier(highest)
                max_curve(curved_mod, orig, new_grades)
            elif curve_option == "3":
                ten_point(orig=orig, new_grades=new_grades)
            else:
                raise KeyError("Must select an option")
        except KeyError:
            flash(message="You must select an option to curve", category="error")
        else:
            grades['curved'] = new_grades
            grades.to_csv(os.path.join(DOWN_PATH, curved_file))
            # Deletes the original file from the server to save space
            # and to follow client privacy.
            delete_uploads(UP_PATH)
            os.chdir(cwd)
        return render_template('download.html', curved_file=curved_file)
    return render_template('home.html')


@views.route('/download', methods=['GET', 'POST'])
def download():
    return render_template('download.html')


def allowed_file(filename):
    return '.' in filename and \
        filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

website/templates/download.html
{% extends 'layout.html' %} {% block title %}Pycurve{% endblock %}{% block content %}
<div class="modal fade" id="instructionModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="instructionModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="instructionModalLabel">Download Instructions</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"
                    aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>
                    Your grades have been curved and you can now download the csv file.
                    ***Note, ensure that you download your file before curving another test***
                </p>
                <p>
                    If you want to curve another test, ensure you have downloaded your file first.
                    All curved tests are erased from the program's downloads folder to save space and keep identities
                    safe.
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div class="vstack gap-2 col-md-5 mx-auto">
    <button onclick="location.href='../static/downloads/{{ curved_file }}'" type="button"
        class="btn btn-download justify-content-center" download="{{ curved_file }}">Download</button>
    <button onclick="location.href=`{{ url_for('views.home')}}`" type="button"
        class="btn btn-home justify-content-center">Curve
        Another
        Test</button>
</div>


{% endblock %}

website/templates/home.html
{% extends 'layout.html' %} {% block title %}Pycurve{% endblock %}{% block content %}
<div class="modal fade" id="instructionModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="instructionModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="instructionModalLabel">Instructions</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"
                    aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Choose the csv file you wish to use from your computer.</p>
                <p class="bold-p">Open the csv and verify the following information or the program will not operate correctly.</p>
                <ul>
                    <li>
                        The column name that is to be curved. (SUPER IMPORTANT!)
                    </li>
                    <li>
                        The grades are in values of percent. If they are points, this won't curve correctly.
                    </li>
                    <li>
                        The file is in csv format. If it is not, the program won't allow you to upload it.
                    </li>
                    <li>
                        All fields are filled out before hitting submit. If not,
                        you will have to refill the form and upload the file.
                    </li>
                </ul>
                <p>If you are unsure of how to make your file a csv, click the link below.</p>
                <a href="https://www.youtube.com/watch?v=_c37nEV65Os">How to create a csv!</a>
                <p class="bold-p">These are the curve options.</p>
                <ul>
                    <li>Option 1 -> The square root curve will take the square root of each score and
                        multiply it by 10.</li>
                    <li>Option 2 -> The max score curve will see which grade range the top score
                        falls in between and subtract the max score from the upper number.
                        This modifier will be added to all grades.</li>
                    <li>Option 3 -> This will just add 10 points to all the scores</li>
                </ul>
                <a href="https://github.com/laffchem/pycurve_gui/blob/main/README.md">Detailed Instructions Here!</a>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

</div>
<form action="" class="row justify-content-center hours-form" method="POST" enctype="multipart/form-data">
    <div class="col-lg-6">
        <div class="form-group">
            <label class="label" for="csv-form">
                Select the csv file.
            </label>
            <input class="form-control" type="file" id="formFile" name="file" accept=".csv">
        </div>
        <div class="form-group">
            <label class="label" for="curved-col">
                Grades Column
            </label>
            <input type="text" class="form-control" id="curved-col" name="curved-col"
                placeholder="Enter the column name you wish to curve.">
        </div>
        <div class="form-group">
            <label class="label" for="curved-file">
                Curved File Name
            </label>
            <input type="text" class="form-control" id="curved-file" name="curved-file"
                placeholder="Enter the filename you wish to download.">
        </div>

        <div class="form-group">
            <label class="label" for="curve-apply">
                Curve
            </label>
            <select class="form-select" id="curve-apply" name="curve-apply" aria-label=".form-select-sm example">
                <option selected>Choose the curve you want to apply.</option>
                <option value="1">Square Root Curve</option>
                <option value="2">Max Score Curve</option>
                <option value="3">10 Point Bump</option>
            </select>
        </div>

        <br>
        <button type="submit" class="btn btn-submit">Submit</button>
        <button type="reset" class="btn btn-reset">Reset</button>

    </div>

</form>















{% endblock %}

website/templates/layout.html
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Home{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- Custom Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;700&display=swap" rel="stylesheet">

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">



    <!-- Custom Styles -->
    <link rel="stylesheet" href="../static/styles.css">


    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/0adf073ec6.js" crossorigin="anonymous"></script>
</head>


<body>
    <div class="topbox">
        <h1>PyCurve</h1>
        <a data-bs-toggle="modal" data-bs-target="#instructionModal" class="instructions"><svg
                xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                class="bi bi-file-earmark-text-fill" viewBox="0 0 16 16">
                <path
                    d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0zM9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1zM4.5 9a.5.5 0 0 1 0-1h7a.5.5 0 0 1 0 1h-7zM4 10.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm.5 2.5a.5.5 0 0 1 0-1h4a.5.5 0 0 1 0 1h-4z" />
            </svg> READ ME!</a>
    </div>
    <!-- Creates pop up with flash messages-->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category == 'error' %}
    <div class="alert alert-danger alert-dismissable fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

        {{ message }}
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissable fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        {{ message }}
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
        integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
        integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous">
    </script>


    <script src="" async defer></script>
</body>

</html>